pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'SE-Capston repository already checked out by Jenkins.'
            }
        }

        stage('Check Java') {
            steps {
                sh 'java -version'
            }
        }

        stage('Check Android SDK') {
            steps {
                sh 'echo ANDROID_HOME=$ANDROID_HOME'
                sh 'ls -la $ANDROID_HOME'
                sh 'ls -la $ANDROID_HOME/platforms'
                sh 'ls -la $ANDROID_HOME/build-tools'
            }
        }

        stage('Build Android APK') {
            steps {
                sh 'chmod +x gradlew'
                sh './gradlew assembleDebug --no-daemon'
            }
        }

    }

    post {

        success {
            archiveArtifacts(
                artifacts: 'app/build/outputs/apk/debug/*.apk',
                fingerprint: true
            )

            echo 'Android APK build successful!'
        }

        failure {
            echo 'Android APK build failed.'
        }

        always {
            echo 'Jenkins pipeline completed.'
        }
    }
}