services:

  # =========================
  # MinIO Object Storage
  # =========================
  minio:
    image: minio/minio:latest
    container_name: se-capston-minio
    ports:
      - "9100:9000"
      - "9101:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - ./storage-data:/data
    command: server /data --console-address ":9001"


  # =========================
  # PostgreSQL Database
  # =========================
  db:
    image: postgres:15
    container_name: se-capston-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: smile_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


  # =========================
  # Node.js Backend
  # =========================
  backend:
    image: node:18
    container_name: se-capston-backend
    working_dir: /app
    volumes:
      - ../backend:/app
      - ../web:/frontend/web
    ports:
      - "5000:5000"
    command: sh -c "npm install && node server.js"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:password123@db:5432/smile_db


  # =========================
  # Jenkins + Android SDK
  # =========================
  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    container_name: se-capston-jenkins
    user: root
    ports:
      - "8180:8080"
      - "50001:50000"
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      ANDROID_HOME: /opt/android-sdk
      ANDROID_SDK_ROOT: /opt/android-sdk


# =========================
# Network
# =========================
networks:
  default:
    name: se-capston-network